nxp/backoffice/urls.py
from django.urls import path, include
from .views import login_view, log_out, index

app_name = "backoffice"
urlpatterns = [
    path('', index, name='index'),
    path('login/', login_view, name='login'),
    path('log_out/', log_out, name='log_out'),
    path('generate-qrcode/', include('nxp.backoffice.generate_qrcode.urls', namespace='generate_qrcode')),
    path('rewards/', include('nxp.backoffice.rewards.urls', namespace='rewards')),
    path('users/', include('nxp.backoffice.users.urls', namespace='users')),
]

nxp/backoffice/users/urls.py
from django.urls import path, include
from .views import *

app_name = "users"
urlpatterns = [
    path("", users, name="users"),
    path('<int:id>/user-detail/', user_detail, name='user_detail'),
]

nxp/frontend/urls.py
from django.urls import path
from .views import *

app_name = "frontend"
urlpatterns = [
    path('', scan, name='scan'),
    # path('', authenticated_scan, name='authenticated_scan'),
    path('redeem/', redeem, name='redeem'),
    path('api-scan/', scan, name='api_scan'),
    path('api-get-info/', get_information, name='get_information'),
    path('api-redeem/', api_redeem, name='api_redeem'),
    path('load-balance/', lazy_load_balance, name='load_balance'),

    # path('redeem/', redeem, name='redeem'),
    # path('api-scan/', api_scan, name='api_scan'),
    # path('api-get-info/', get_information, name='get_information'),
    # path('api-redeem/', api_redeem, name='api_redeem'),
    # path('load-balance/', lazy_load_balance, name='load_balance'),
]

nxp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "NXP Admin"
admin.site.site_title = "NXP Admin Portal"
admin.site.index_title = "Welcome to NXP Admin Portal"

urlpatterns = [
    path('', include('nxp.frontend.urls', namespace='frontend')),
    path('nxp-admin/', admin.site.urls),
    path('backoffice/', include('nxp.backoffice.urls', namespace='backoffice')),

    # redirect semua ke FE Home
    # path('nxp-admin/', include('nxp.frontend.urls', namespace='frontend2')),
    # path('backoffice/', include('nxp.frontend.urls', namespace='frontend3')),
    path('login', include('nxp.frontend.urls', namespace='frontend4')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nxp/apps/dealer/models.py
from django.db import models

from nxp.core.utils import FilenameGenerator


class Dealer(models.Model):
    code = models.CharField(max_length=50, unique=True, db_index=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

nxp/apps/serial_number/models.py
from django.db import models



class SerialNumber(models.Model):
    serial_number = models.CharField(max_length=50, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    STATUS = (
        ('new', 'new'),
        ('redeem', 'redeem'),
    )
    status = models.CharField(max_length=10, choices=STATUS, default='new')
    TYPE = (
        ('U', 'U'), #user
        ('D', 'D'), #dealer
    )
    type = models.CharField(max_length=10, choices=TYPE, default='U')
    order = models.IntegerField(blank=True, null=True)
    value = models.IntegerField(default=400)
    
    def __str__(self):
        return self.serial_number

nxp/apps/settings/models.py
from nxp.core.utils import FilenameGenerator
from django.db import models


class Settings(models.Model):
    TYPE = (
        ('seo_description', 'SEO Description'),
        ('seo_title', 'SEO Title'),
        ('seo_keywords', 'SEO Keywords'),
        ('seo_image', 'SEO Image'),
        ('seo_fb_id', 'SEO FbID'),
    )
    name = models.CharField(max_length=254, choices=TYPE, unique=True)
    text_value = models.TextField(blank=True, null=True)
    img_value =  models.ImageField(upload_to=FilenameGenerator(
        prefix='settings'), blank=True, null=True)

    def __str__(self):
        return self.name

nxp/backoffice/forms.py
from django import forms
from django.contrib import auth


class LoginForm(auth.forms.AuthenticationForm):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

    def clean(self):
        return super(LoginForm, self).clean()

nxp/apps/reward/views.py
from django.shortcuts import render

# Create your views here.

nxp/apps/serial_number/views.py
from django.shortcuts import render

# Create your views here.

nxp/apps/settings/views.py
from django.shortcuts import render

# Create your views here.

nxp/apps/user/views.py
from django.shortcuts import render

# Create your views here.

nxp/backoffice/generate_qrcode/views.py
import string
import random
import csv
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from django.http import JsonResponse

from nxp.apps.serial_number.models import SerialNumber
from nxp.apps.user.decorators import login_validate

from django.http import HttpResponse
from sequences import get_next_value
from django.db import transaction



@login_validate
def index(request):
    serials = SerialNumber.objects.all().order_by('-order')
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    start = request.GET.get("start", 0)
    end = request.GET.get("end", 0)

    if start and end:
        _filter = list(range(int(start), int(end)+1))
        serials = serials.filter(order__in=_filter)
    

    if search:
        serials = serials.filter(serial_number=search)

    status = request.GET.get("status")
    if status:
        serials = serials.filter(status=status)

    type = request.GET.get("type")
    if type:
        serials = serials.filter(type=type)

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
            # headers={'Content-Disposition': 'attachment; filename="qrcode.csv"'},
        )
        writer = csv.writer(response)
        writer.writerow(['No', 'Qr-Code', 'Status'])
        idx = 0
        for sr in serials:
            idx += 1
            writer.writerow([idx, sr.serial_number, sr.status])
        return response

    results_per_page = 60
    new_count = serials.filter(status="new").count()
    redeem_count = serials.filter(status="redeem").count()

    paginator = Paginator(serials, results_per_page)
    try:
        serials = paginator.get_page(page)
    except PageNotAnInteger:
        serials = paginator.get_page(1)
    except EmptyPage:
        serials = paginator.get_page(paginator.num_pages)

    context = {
        "serials": serials,
        "title": "Serial Number",
        "filter": {"search": search, "status": status, "type": type, "start": start, "end": end},
        "new_count": new_count,
        "redeem_count": redeem_count,
    }

    return TemplateResponse(request, "backoffice/serial/index.html", context)


def generate_serial(num):
    serials = []
    serials_str = []
    rp1000 = [1000] * int (1 * num)
    # rp500 = [500] * int (0.04 * num)
    # rp400 = [400] * int (0.93 * num)
    # list_value = rp1000 + rp500 + rp400
    list_value = rp1000

    for _ in range(num):
        duplicate = True
        while duplicate:
            code = "".join([random.choice(string.ascii_uppercase + string.digits) for i in range(
                10)])
            exists = code in serials_str
            serial = SerialNumber.objects.filter(serial_number=code).first()
            if not serial and not exists:
                serials_str.append(code)
                duplicate = False
        serial = SerialNumber(
            serial_number=code, order=get_next_value("order"), value=list_value.pop())
        serials.append(serial)
    SerialNumber.objects.bulk_create(serials)


def generate(request):
    amount = request.POST.get('amount', 0)
    if not int(amount) % 100 == 0:
        return JsonResponse({"status": "Jumlah harus kelipatan 100"}, safe=False, status=400)
    _type = request.POST.get('type')
    with transaction.atomic():
        generate_serial(int(amount))
    return JsonResponse({"status": "OK"}, safe=False)


def print_barcode(request):
    start = request.GET.get("start", 0)
    end = request.GET.get("end", 0)
    _filter = list(range(int(start), int(end)+1))
    serials = SerialNumber.objects.filter(order__in=_filter).order_by('-order')

    context = {
        "serials": serials,
        "title": "Print Number",
    }
    return TemplateResponse(request, "backoffice/serial/print.html", context)

nxp/backoffice/rewards/views.py
import csv
import datetime
from django.http import JsonResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.reward.models import Redeem, Scan
from nxp.apps.user.decorators import login_validate
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.http import HttpResponse


@login_validate
def redeem(request):
    redeems = Redeem.objects.select_related('user').order_by("-id")
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        redeems = redeems.filter(Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search))

    ewallet = request.GET.get("ewallet")
    if ewallet:
        redeems = redeems.filter(wallet_type=ewallet)
    status = request.GET.get("status")
    if status:
        redeems = redeems.filter(status=status)

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="redeem.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name', 'Nominal', 'E-Wallet', 'Status'])
        idx = 0
        for sr in redeems:
            idx += 1
            writer.writerow([idx, sr.user.name, sr.dealer_code, sr.user.mobile_number,
                             sr.value, sr.get_wallet_type_display(), sr.status])
        return response

    results_per_page = 30
    new_count = redeems.filter(status="new").count()
    paid_count = redeems.filter(status="paid").count()
    cancel_count = redeems.filter(status="paid").count()

    paginator = Paginator(redeems, results_per_page)
    try:
        redeems = paginator.get_page(page)
    except PageNotAnInteger:
        redeems = paginator.get_page(1)
    except EmptyPage:
        redeems = paginator.get_page(paginator.num_pages)

    context = {
        "redeems": redeems,
        "title": "Redeem",
        "filter": {"search": search, "status": status, "ewallet": ewallet},
        "new_count": new_count,
        "paid_count": paid_count,
        "cancel_count": cancel_count,
    }
    return TemplateResponse(request, "backoffice/rewards/index.html", context)


@login_validate
def transactions(request):
    scans = Scan.objects.all().order_by("-id").select_related('user')\
        .select_related('serial_number').order_by('-datetime')
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    start = request.GET.get("start", "")
    end = request.GET.get("end", "")
    if search:
        scans = scans.filter(
            Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search) | Q(serial_number__serial_number__icontains=search))

    if start and end:
        scans = scans.filter(datetime__range=[start, end])

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="transactions.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Serial', 'Name', 'Date', 'Value'])
        idx = 0
        
        for sr in scans:
            idx += 1
            _datetime = sr.datetime.strftime("%m/%d/%Y, %H:%M")
            _datetime = datetime.datetime.strptime(_datetime, "%m/%d/%Y, %H:%M")
            writer.writerow([idx, sr.serial_number, sr.user.name, _datetime,
                             sr.serial_number.value])
        return response

    results_per_page = 30
    paginator = Paginator(scans, results_per_page)
    try:
        scans = paginator.get_page(page)
    except PageNotAnInteger:
        scans = paginator.get_page(1)
    except EmptyPage:
        scans = paginator.get_page(paginator.num_pages)

    context = {
        "scans": scans,
        "title": "Transactions",
        "filter": {"search": search, "start": start, "end": end},
    }
    return TemplateResponse(request, "backoffice/rewards/transactions.html", context)

@login_validate
def redeem_detail(request, id):
    redeem = Redeem.objects.get(id=id)
    context = {
        "redeem": redeem,
        'vrer':  request.session
    }
    return TemplateResponse(request, "backoffice/rewards/redeem-detail.html", context)


@login_validate
def set_as_paid(request, id):
    redeem = get_object_or_404(Redeem, id=id)
    if redeem.status == 'paid':
        return JsonResponse({"message": "redeem already paid"}, status = 400)
    else:
        redeem.status = 'paid'
        redeem.paid_datetime = timezone.now()
        redeem.admin = request.user
        redeem.save()
        return JsonResponse({"message": "redeem already paid"}, status = 200)

    

nxp/backoffice/users/views.py
import csv
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.user.models import User
from nxp.apps.reward.models import Scan
from nxp.apps.user.decorators import login_validate
from django.http import HttpResponse


@login_validate
def users(request):
    users = User.objects.all().order_by("-id").exclude(is_superuser=True)
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        users = users.filter(
            Q(name__icontains=search) | Q(mobile_number__icontains=search) |
            Q(dealer_name__icontains=search)
        )

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="users.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name'])
        idx = 0
        for sr in users:
            idx += 1
            writer.writerow([idx, sr.name, sr.mobile_number, sr.dealer_name])
        return response

    results_per_page = 30
    paginator = Paginator(users, results_per_page)
    try:
        users = paginator.get_page(page)
    except PageNotAnInteger:
        users = paginator.get_page(1)
    except EmptyPage:
        users = paginator.get_page(paginator.num_pages)

    context = {
        "users": users,
        "title": "User",
        "filter": {"search": search},
    }
    return TemplateResponse(request, "backoffice/users/index.html", context)

@login_validate
def user_detail(request, id):
    user = User.objects.get(id=id)
    scans = Scan.objects.filter(user=user).order_by('-datetime').select_related('serial_number')
    context = {
        "user": user,
        "title": "User Detail",
        "scans": scans[0:8]
    }
    return TemplateResponse(request, "backoffice/users/user-detail.html", context)

nxp/backoffice/views.py
from django.apps.registry import apps
from django.contrib import messages
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from nxp.apps.reward.models import Redeem
from nxp.apps.user.decorators import login_validate
from nxp.backoffice.forms import LoginForm

get_model = apps.get_model


def login_view(request):
    auth_form = LoginForm(data=request.POST or None)
    if auth_form.is_valid():
        login(request, auth_form.get_user())
        auth_form.get_user()
        return redirect("backoffice:index")
    else:
        messages.error(request, "Username and Password are incorrect")

    list(messages.get_messages(request))
    context = dict(auth_form=auth_form,)
    return TemplateResponse(request, "backoffice/login.html", context)


def log_out(request):
    logout(request)
    return redirect("backoffice:login")


@login_validate
def index(request):
    redeems = Redeem.objects.all()
    context = dict(
        new_count=redeems.filter(status="new").count(),
        paid_count=redeems.filter(status="paid").count(),
        cancelled_count=redeems.filter(status="cancelled").count(),
        ovo_count=redeems.filter(wallet_type="ovo").count(),
        gopay_count=redeems.filter(wallet_type="gopay").count(),
        dana_count=redeems.filter(wallet_type="dana").count(),
        shopee_pay_count=redeems.filter(wallet_type="shopee_pay").count(),
        title='Dashboard'
    )
    return TemplateResponse(request, "backoffice/index.html", context)

nxp/templates/backoffice/rewards/index.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% load humanize %}
{% load templatehelpers %}
{% block title%} {{ title }} {% endblock %}
{% block content %}
<div class="box">
    <div class="box-inner">
      <div class="box-title">
        <h2>Redeem</h2>
      </div>
      <div class="box-title">
        <form method="GET" action="">
          <div class="row">
            <div class="col-sm-3">
              <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="User / Mobile Number..." value="{{ filter.search }}">
              </div>
            </div>

            <div class="col-sm-2">
              <div class="input-group">
                <select class="form-control" name="ewallet">
                  <option value=""> .. eWallet .. </option>
                  <option value="gopay" {% if filter.ewallet == "gopay" %} selected {% endif %}>Gopay</option>
                  <option value="ovo" {% if filter.ewallet == "ovo" %} selected {% endif %}>OVO</option>
                  <option value="dana" {% if filter.ewallet == "dana" %} selected {% endif %}>Dana</option>
                  <option value="shopee_pay" {% if filter.ewallet == "shopee_pay" %} selected {% endif %}>Shopee Pay</option>
                </select>
              </div>
            </div>

            <div class="col-sm-2">
              <div class="input-group">
                <select class="form-control" name="status">
                  <option value=""> .. status .. </option>
                  <option value="new" {% if filter.status == "new" %} selected {% endif %}>New</option>
                  <option value="paid" {% if filter.status == "paid" %} selected {% endif %}>Paid</option>
                  <option value="cancelled" {% if filter.status == "cancelled" %} selected {% endif %}>Cancelled</option>
                </select>
              </div>
            </div>

            <div class="col-sm-2">
              <div class="input-group">
                <select class="form-control" name="action">
                  <option value="filter" {% if filter.action == "filter" %} selected {% endif %} selected>Filter</option>
                  <option value="export" {% if filter.action == "export" %} selected {% endif %} >Export CSV</option>
                </select>
              </div>
            </div>

            <div class="col-sm-2">
              <button type="submit" id="btn-search-fix-h" class="btn btn-primary">
                submit
              </button>
            </div>

            <div class="col-sm-3">
              <P>New: {{new_count}} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Paid: {{paid_count}} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Cancel: {{cancel_count}}</P>
            </div>

          </div>
        </form>
      </div>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>No</th>
            <th>Name</th>
            <th>Dealer Code</th>
            <th>Mobile Number</th>
            <th>Nominal</th>
            <th>E-Wallet</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
        {% for redeem in redeems %}
          <tr>
            <th scope="row"><a href="{% url 'backoffice:rewards:redeem_detail' redeem.id %}"> {{ forloop.counter }}</a></th>
            <td><a href="{% url 'backoffice:rewards:redeem_detail' redeem.id %}"> {{ redeem.user.name }} </a></td>
            <td>{{ redeem.dealer_code }} </td>
            <td>{{ redeem.user.mobile_number }}</td>
            <td>{{ redeem.value|intcomma }}</td>
            <td>{{ redeem.get_wallet_type_display }}</td>
            <td>{{ redeem.status }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
  
      <div class="pull-right">
        <p>Page {{ redeems.number }} of {{ redeems.paginator.num_pages }}</p>
        <nav aria-label="">
          <ul class="pagination">
            {% if redeems.has_previous %}
            <li class="page-item"><a class="page-link" href="{% relative_url 1 'page' request.GET.urlencode %}">First</a>
            </li>
            <li class="page-item"><a class="page-link"
                href="{% relative_url redeems.previous_page_number 'page' request.GET.urlencode %}">Previous</a></li>
            {% endif %}
            <!-- {% for i in redeems.paginator.page_range %}
            <li class="page-item"><a class="page-link {% if redeems.number == i %}is-active{% endif %}"
                href="{% relative_url i 'page' request.GET.urlencode %}">{{forloop.counter}}</a></li>
            {% endfor %} -->
            {% if redeems.has_next %}
            <li class="page-item"><a class="page-link"
                href="{% relative_url redeems.next_page_number 'page' request.GET.urlencode %}">Next</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>

  </div>
{% endblock %}

nxp/templates/backoffice/rewards/redeem-detail.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% block title%} {{ title }} {% endblock %}
{% block content %}
{% load humanize %}
<div class="box margin-top-profile">
  <div class="profile__content">
    <div class="profile__bio">
      <div class="my-sep1">
        <span>
          {{ redeem.user.name }}
        </span>
      </div>
      <h3 class="profile__name">Rp. {{ redeem.value|intcomma }}</h3>
      <p>{{ redeem.user.mobile_number }} - {{ redeem.get_status_display }} - {{ redeem.get_wallet_type_display }}
      </p>
      <hr>
      <div class="overview align-left">
        <div class="row">
          <div class="col-sm-6">
            <ul>
              <li><strong>e-Wallet</strong><span>{{ redeem.get_wallet_type_display }}</span></li>
              <li><strong>Mobile Number</strong><span>{{ redeem.user.mobile_number | default:'-' }}</span>
              </li>
              <li><strong>Dealer Code</strong><span>{{ redeem.dealer_code | default:'-' }}</span></li>
            </ul>
          </div>
          <div class="col-sm-6">
            <ul>
              <li><strong>Status</strong><span>{{ redeem.get_status_display | default:'-' }}</span></li>
              <li><strong>Redeem Date</strong><span>{{ redeem.datetime | default:'-' }}</span></li>
              <li><strong>Paid Date</strong><span>{{ redeem.paid_datetime | default:'-' }}</span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div style="text-align: center;">
    <button type="Set As Paid" id="btnSetAsPaid" class="btn btn-primary">
      Set As Paid
    </button>
  </div>
</div>
{% endblock %}

{% block script %}
{% csrf_token %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static 'js/loading.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript">
  $(function () {
    console.log('{{ request.session }}')
    $('#btnSetAsPaid').on('click', function (e) {
      //   $("#content").loading({
      //     stoppable: true
      //   }); 

      e.preventDefault();
      var url = "{% url 'backoffice:rewards:set_as_paid' redeem.id %}";
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      $.ajax({
        type: 'get',
        url: url,
        success: function (data) {
          console.log(data)
          window.location.reload();
          alert("Transaksi berhasil");
        },
        error: function (error) {
          // $('#content').loading('stop');
          alert(error.responseText);
        }
      });
    })
  }(jQuery));
</script>
{% endblock %}

nxp/templates/backoffice/rewards/transactions.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% load templatehelpers %}
{% load humanize %}
{% block title%} {{ title }} {% endblock %}
{% block content %}
<div class="box">
    <div class="box-inner">
      <div class="box-title">
        <h2>Transactions</h2>
      </div>
      <div class="box-title">
        <form method="GET" action="">
          <div class="row">
            <div class="col-sm-2">
              <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="User / Mobile Number / Serial " value="{{ filter.search }}">
              </div>
            </div>

            <div class="col-sm-2">
              <div class="input-group">
                <input type="date" name="start" class="form-control" placeholder="Start" value="{{ filter.start }}">
              </div>
            </div>
            <div class="col-sm-2">
              <div class="input-group">
                <input type="date" name="end" class="form-control" placeholder="End" value="{{ filter.end }}">
              </div>
            </div>

            <div class="col-sm-2">
              <div class="input-group">
                <select class="form-control" name="action">
                  <option value="filter" {% if filter.action == "filter" %} selected {% endif %} selected>Filter</option>
                  <option value="export" {% if filter.action == "export" %} selected {% endif %} >Export CSV</option>
                </select>
              </div>
            </div>

            <div class="col-sm-2">
              <button type="submit" id="btn-search-fix-h" class="btn btn-primary">
                submit
              </button>
            </div>
          </div>
        </form>
      </div>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>No</th>
            <th>Serial</th>
            <th>Name</th>
            <th>Date</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
        {% for redeem in scans %}
          <tr>
            <th scope="row"><a href="{% url 'backoffice:users:user_detail' redeem.user.id %}">{{ forloop.counter }}</a></th>
            <td><a href="{% url 'backoffice:users:user_detail' redeem.user.id %}">{{ redeem.serial_number }}</a></td>
            <td>{{ redeem.user.name }}</td>
            <td>{{ redeem.datetime }}</td>
            <td>{{ redeem.serial_number.value|intcomma }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
  
      <div class="pull-right">
        <p>Page {{ scans.number }} of {{ scans.paginator.num_pages }}</p>
        <nav aria-label="">
          <ul class="pagination">
            {% if scans.has_previous %}
            <li class="page-item"><a class="page-link" href="{% relative_url 1 'page' request.GET.urlencode %}">First</a>
            </li>
            <li class="page-item"><a class="page-link"
                href="{% relative_url scans.previous_page_number 'page' request.GET.urlencode %}">Previous</a></li>
            {% endif %}
            <!-- {% for i in scans.paginator.page_range %}
            <li class="page-item"><a class="page-link {% if scans.number == i %}is-active{% endif %}"
                href="{% relative_url i 'page' request.GET.urlencode %}">{{forloop.counter}}</a></li>
            {% endfor %} -->
            {% if scans.has_next %}
            <li class="page-item"><a class="page-link"
                href="{% relative_url scans.next_page_number 'page' request.GET.urlencode %}">Next</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>

  </div>
{% endblock %}