nxp/backoffice/urls.py
from django.urls import path, include
from .views import login_view, log_out, index

app_name = "backoffice"
urlpatterns = [
    path('', index, name='index'),
    path('login/', login_view, name='login'),
    path('log_out/', log_out, name='log_out'),
    path('generate-qrcode/', include('nxp.backoffice.generate_qrcode.urls', namespace='generate_qrcode')),
    path('rewards/', include('nxp.backoffice.rewards.urls', namespace='rewards')),
    path('users/', include('nxp.backoffice.users.urls', namespace='users')),
]

nxp/backoffice/users/urls.py
from django.urls import path, include
from .views import *

app_name = "users"
urlpatterns = [
    path("", users, name="users"),
    path('<int:id>/user-detail/', user_detail, name='user_detail'),
]

nxp/frontend/urls.py
from django.urls import path
from .views import *

app_name = "frontend"
urlpatterns = [
    path('', scan, name='scan'),
    # path('', authenticated_scan, name='authenticated_scan'),
    path('redeem/', redeem, name='redeem'),
    path('api-scan/', scan, name='api_scan'),
    path('api-get-info/', get_information, name='get_information'),
    path('api-redeem/', api_redeem, name='api_redeem'),
    path('load-balance/', lazy_load_balance, name='load_balance'),

    # path('redeem/', redeem, name='redeem'),
    # path('api-scan/', api_scan, name='api_scan'),
    # path('api-get-info/', get_information, name='get_information'),
    # path('api-redeem/', api_redeem, name='api_redeem'),
    # path('load-balance/', lazy_load_balance, name='load_balance'),
]

nxp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "NXP Admin"
admin.site.site_title = "NXP Admin Portal"
admin.site.index_title = "Welcome to NXP Admin Portal"

urlpatterns = [
    path('', include('nxp.frontend.urls', namespace='frontend')),
    path('nxp-admin/', admin.site.urls),
    path('backoffice/', include('nxp.backoffice.urls', namespace='backoffice')),

    # redirect semua ke FE Home
    # path('nxp-admin/', include('nxp.frontend.urls', namespace='frontend2')),
    # path('backoffice/', include('nxp.frontend.urls', namespace='frontend3')),
    path('login', include('nxp.frontend.urls', namespace='frontend4')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nxp/apps/dealer/models.py
from django.db import models

from nxp.core.utils import FilenameGenerator


class Dealer(models.Model):
    code = models.CharField(max_length=50, unique=True, db_index=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

nxp/backoffice/forms.py
from django import forms
from django.contrib import auth


class LoginForm(auth.forms.AuthenticationForm):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

    def clean(self):
        return super(LoginForm, self).clean()

nxp/backoffice/generate_qrcode/forms.py
# from SahabatElvineDjango.apps.news.models import News
# from django import forms


# class AddNewsForm(forms.ModelForm):
#     name = forms.CharField(widget=forms.TextInput(
#         attrs={'class': 'form-control'}), required=False)
#     description = forms.CharField(
#         widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)
#     short_description = forms.CharField(
#         widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
#     picture1 = forms.ImageField(
#         required=True, help_text="Ukuran gambar harus 500PX * 270PX")
#     picture2 = forms.ImageField(required=False)
#     picture3 = forms.ImageField(required=False)
#     date = forms.ImageField(required=False)

#     class Meta:
#         model = News
#         fields = '__all__'

#     def clean_picture1(self):
#         picture1 = self.cleaned_data.get('picture1', False)
#         if picture1:
#             if picture1.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture1 file too large ( > 0.5mb )")
#         return picture1

#     def clean_picture2(self):
#         picture2 = self.cleaned_data.get('picture2', False)
#         if picture2:
#             if picture2.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture2 file too large ( > 0.5mb )")
#         return picture2

#     def clean_picture3(self):
#         picture3 = self.cleaned_data.get('picture3', False)
#         if picture3:
#             if picture3.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture3 file too large ( > 0.5mb )")
#         return picture3

nxp/apps/reward/views.py
from django.shortcuts import render

# Create your views here.

nxp/apps/serial_number/views.py
from django.shortcuts import render

# Create your views here.

nxp/apps/settings/views.py
from django.shortcuts import render

# Create your views here.

nxp/apps/user/views.py
from django.shortcuts import render

# Create your views here.

nxp/backoffice/generate_qrcode/views.py
import string
import random
import csv
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from django.http import JsonResponse

from nxp.apps.serial_number.models import SerialNumber
from nxp.apps.user.decorators import login_validate

from django.http import HttpResponse
from sequences import get_next_value
from django.db import transaction



@login_validate
def index(request):
    serials = SerialNumber.objects.all().order_by('-order')
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    start = request.GET.get("start", 0)
    end = request.GET.get("end", 0)

    if start and end:
        _filter = list(range(int(start), int(end)+1))
        serials = serials.filter(order__in=_filter)
    

    if search:
        serials = serials.filter(serial_number=search)

    status = request.GET.get("status")
    if status:
        serials = serials.filter(status=status)

    type = request.GET.get("type")
    if type:
        serials = serials.filter(type=type)

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
            # headers={'Content-Disposition': 'attachment; filename="qrcode.csv"'},
        )
        writer = csv.writer(response)
        writer.writerow(['No', 'Qr-Code', 'Status'])
        idx = 0
        for sr in serials:
            idx += 1
            writer.writerow([idx, sr.serial_number, sr.status])
        return response

    results_per_page = 60
    new_count = serials.filter(status="new").count()
    redeem_count = serials.filter(status="redeem").count()

    paginator = Paginator(serials, results_per_page)
    try:
        serials = paginator.get_page(page)
    except PageNotAnInteger:
        serials = paginator.get_page(1)
    except EmptyPage:
        serials = paginator.get_page(paginator.num_pages)

    context = {
        "serials": serials,
        "title": "Serial Number",
        "filter": {"search": search, "status": status, "type": type, "start": start, "end": end},
        "new_count": new_count,
        "redeem_count": redeem_count,
    }

    return TemplateResponse(request, "backoffice/serial/index.html", context)


def generate_serial(num):
    serials = []
    serials_str = []
    rp1000 = [1000] * int (1 * num)
    # rp500 = [500] * int (0.04 * num)
    # rp400 = [400] * int (0.93 * num)
    # list_value = rp1000 + rp500 + rp400
    list_value = rp1000

    for _ in range(num):
        duplicate = True
        while duplicate:
            code = "".join([random.choice(string.ascii_uppercase + string.digits) for i in range(
                10)])
            exists = code in serials_str
            serial = SerialNumber.objects.filter(serial_number=code).first()
            if not serial and not exists:
                serials_str.append(code)
                duplicate = False
        serial = SerialNumber(
            serial_number=code, order=get_next_value("order"), value=list_value.pop())
        serials.append(serial)
    SerialNumber.objects.bulk_create(serials)


def generate(request):
    amount = request.POST.get('amount', 0)
    if not int(amount) % 100 == 0:
        return JsonResponse({"status": "Jumlah harus kelipatan 100"}, safe=False, status=400)
    _type = request.POST.get('type')
    with transaction.atomic():
        generate_serial(int(amount))
    return JsonResponse({"status": "OK"}, safe=False)


def print_barcode(request):
    start = request.GET.get("start", 0)
    end = request.GET.get("end", 0)
    _filter = list(range(int(start), int(end)+1))
    serials = SerialNumber.objects.filter(order__in=_filter).order_by('-order')

    context = {
        "serials": serials,
        "title": "Print Number",
    }
    return TemplateResponse(request, "backoffice/serial/print.html", context)

nxp/backoffice/rewards/views.py
import csv
import datetime
from django.http import JsonResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.reward.models import Redeem, Scan
from nxp.apps.user.decorators import login_validate
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.http import HttpResponse


@login_validate
def redeem(request):
    redeems = Redeem.objects.select_related('user').order_by("-id")
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        redeems = redeems.filter(Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search))

    ewallet = request.GET.get("ewallet")
    if ewallet:
        redeems = redeems.filter(wallet_type=ewallet)
    status = request.GET.get("status")
    if status:
        redeems = redeems.filter(status=status)

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="redeem.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name', 'Nominal', 'E-Wallet', 'Status'])
        idx = 0
        for sr in redeems:
            idx += 1
            writer.writerow([idx, sr.user.name, sr.dealer_code, sr.user.mobile_number,
                             sr.value, sr.get_wallet_type_display(), sr.status])
        return response

    results_per_page = 30
    new_count = redeems.filter(status="new").count()
    paid_count = redeems.filter(status="paid").count()
    cancel_count = redeems.filter(status="paid").count()

    paginator = Paginator(redeems, results_per_page)
    try:
        redeems = paginator.get_page(page)
    except PageNotAnInteger:
        redeems = paginator.get_page(1)
    except EmptyPage:
        redeems = paginator.get_page(paginator.num_pages)

    context = {
        "redeems": redeems,
        "title": "Redeem",
        "filter": {"search": search, "status": status, "ewallet": ewallet},
        "new_count": new_count,
        "paid_count": paid_count,
        "cancel_count": cancel_count,
    }
    return TemplateResponse(request, "backoffice/rewards/index.html", context)


@login_validate
def transactions(request):
    scans = Scan.objects.all().order_by("-id").select_related('user')\
        .select_related('serial_number').order_by('-datetime')
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    start = request.GET.get("start", "")
    end = request.GET.get("end", "")
    if search:
        scans = scans.filter(
            Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search) | Q(serial_number__serial_number__icontains=search))

    if start and end:
        scans = scans.filter(datetime__range=[start, end])

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="transactions.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Serial', 'Name', 'Date', 'Value'])
        idx = 0
        
        for sr in scans:
            idx += 1
            _datetime = sr.datetime.strftime("%m/%d/%Y, %H:%M")
            _datetime = datetime.datetime.strptime(_datetime, "%m/%d/%Y, %H:%M")
            writer.writerow([idx, sr.serial_number, sr.user.name, _datetime,
                             sr.serial_number.value])
        return response

    results_per_page = 30
    paginator = Paginator(scans, results_per_page)
    try:
        scans = paginator.get_page(page)
    except PageNotAnInteger:
        scans = paginator.get_page(1)
    except EmptyPage:
        scans = paginator.get_page(paginator.num_pages)

    context = {
        "scans": scans,
        "title": "Transactions",
        "filter": {"search": search, "start": start, "end": end},
    }
    return TemplateResponse(request, "backoffice/rewards/transactions.html", context)

@login_validate
def redeem_detail(request, id):
    redeem = Redeem.objects.get(id=id)
    context = {
        "redeem": redeem,
        'vrer':  request.session
    }
    return TemplateResponse(request, "backoffice/rewards/redeem-detail.html", context)


@login_validate
def set_as_paid(request, id):
    redeem = get_object_or_404(Redeem, id=id)
    if redeem.status == 'paid':
        return JsonResponse({"message": "redeem already paid"}, status = 400)
    else:
        redeem.status = 'paid'
        redeem.paid_datetime = timezone.now()
        redeem.admin = request.user
        redeem.save()
        return JsonResponse({"message": "redeem already paid"}, status = 200)

    

nxp/backoffice/users/views.py
import csv
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.user.models import User
from nxp.apps.reward.models import Scan
from nxp.apps.user.decorators import login_validate
from django.http import HttpResponse


@login_validate
def users(request):
    users = User.objects.all().order_by("-id").exclude(is_superuser=True)
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        users = users.filter(
            Q(name__icontains=search) | Q(mobile_number__icontains=search) |
            Q(dealer_name__icontains=search)
        )

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="users.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name'])
        idx = 0
        for sr in users:
            idx += 1
            writer.writerow([idx, sr.name, sr.mobile_number, sr.dealer_name])
        return response

    results_per_page = 30
    paginator = Paginator(users, results_per_page)
    try:
        users = paginator.get_page(page)
    except PageNotAnInteger:
        users = paginator.get_page(1)
    except EmptyPage:
        users = paginator.get_page(paginator.num_pages)

    context = {
        "users": users,
        "title": "User",
        "filter": {"search": search},
    }
    return TemplateResponse(request, "backoffice/users/index.html", context)

@login_validate
def user_detail(request, id):
    user = User.objects.get(id=id)
    scans = Scan.objects.filter(user=user).order_by('-datetime').select_related('serial_number')
    context = {
        "user": user,
        "title": "User Detail",
        "scans": scans[0:8]
    }
    return TemplateResponse(request, "backoffice/users/user-detail.html", context)

nxp/backoffice/views.py
from django.apps.registry import apps
from django.contrib import messages
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from nxp.apps.reward.models import Redeem
from nxp.apps.user.decorators import login_validate
from nxp.backoffice.forms import LoginForm

get_model = apps.get_model


def login_view(request):
    auth_form = LoginForm(data=request.POST or None)
    if auth_form.is_valid():
        login(request, auth_form.get_user())
        auth_form.get_user()
        return redirect("backoffice:index")
    else:
        messages.error(request, "Username and Password are incorrect")

    list(messages.get_messages(request))
    context = dict(auth_form=auth_form,)
    return TemplateResponse(request, "backoffice/login.html", context)


def log_out(request):
    logout(request)
    return redirect("backoffice:login")


@login_validate
def index(request):
    redeems = Redeem.objects.all()
    context = dict(
        new_count=redeems.filter(status="new").count(),
        paid_count=redeems.filter(status="paid").count(),
        cancelled_count=redeems.filter(status="cancelled").count(),
        ovo_count=redeems.filter(wallet_type="ovo").count(),
        gopay_count=redeems.filter(wallet_type="gopay").count(),
        dana_count=redeems.filter(wallet_type="dana").count(),
        shopee_pay_count=redeems.filter(wallet_type="shopee_pay").count(),
        title='Dashboard'
    )
    return TemplateResponse(request, "backoffice/index.html", context)

nxp/templates/frontend/redeem.html
{% extends 'frontend/base.html' %}
{% load humanize %}
{% load static %}
{% block content %}
<section class="row justify-content-lg-center">
  <div class="col-sm-12 col-md-6 col-lg-4 content header">
    <a class="menu" href="{% url 'frontend:scan' %}"> Tukar Poin </a>
    <a class="menu" href="{% url 'frontend:redeem' %}"> Pencairan Poin </a>
  </div>
</section>

<section class="row" id="information" hidden>
  <div class="col-sm-12 col-md-6 col-lg-4 content present">
    <p class="identity">Identitas Anda:</p>
    <p class="mobile_number"></p>
    <p class="name"></p>
    <div class="reward-wrapper">
      <img class="reward-img" src="{% static '/images/reward.png' %}" />
      <p class="reward"></p>
    </div>
  </div>
</section>

<section class="row">
  <div class="col-sm-12 col-md-6 col-lg-4 content search-content">
    <form class="search-form" method="POST" id="main-search-form" name="search-form" action="">
      {% csrf_token %}
      <p class="mobile_label">Masukkan Nomor HP Anda</p>
      <div class="form-group" style="display: flex; flex-direction: row; justify-content: space-between;">
        <label for="mobile_number"></label>
        <input type="text" name="mobile_number" id="mobile_number" placeholder="Nomor HP" required="required">
        <button type="button" id="searchButton" class="search-button"><i class="fa fa-search"></i></button>
      </div>

      <div class="form-group">
        <label for="dealer_code"></label>
        <input type="text" name="dealer_code" id="dealer_code" placeholder="Kode Dealer" hidden>
      </div>

      <div class="form-group">
        <label for="nominal_value"></label>
        <input type="number" name="nominal_value" id="nominal_value" placeholder="Jumlah Redeem" required="required"
          hidden>
        <p style="font-size: 13px color: 'white';" id="nominal_value2" hidden>Minimal Rp. 10.000</p>
      </div>

      <div class="row wallet-type" id="walletType" hidden>
        <div class="col-sm-6 form-check">
          <label class="from-check-wrapper">
            <input class="form-check-input" type="radio" name="wallet_type" id="exampleRadios1" value="gopay" checked>
            <img class="payment-img" src="{% static '/images/gopay.png' %}" />
          </label>
        </div>
        <div class="col-sm-6 form-check ">
          <label class="from-check-wrapper">
            <input class="form-check-input" type="radio" name="wallet_type" id="exampleRadios2" value="ovo">
            <img class="payment-img" src="{% static '/images/ovo.png' %}" />
          </label>
        </div>
        <div class="col-sm-6 form-check ">
          <label class="from-check-wrapper">
            <input class="form-check-input" type="radio" name="wallet_type" id="exampleRadios2" value="dana">
            <img class="payment-img" src="{% static '/images/dana.png' %}" />
          </label>
        </div>
        <div class="col-sm-6 form-check ">
          <label class="from-check-wrapper">
            <input class="form-check-input" type="radio" name="wallet_type" id="exampleRadios2" value="shopee_pay">
            <img class="payment-img" src="{% static '/images/shopee.png' %}" />
          </label>
        </div>
      </div>
      <div class="form-group" hidden id="btnRedeem">
        <button type="submit" class="btn-submit">Redeem</button>
      </div>
    </form>
  </div>
</section>

<section class="row" id="balanceInfo" hidden>
  <div class="col-sm-12 col-md-6 col-lg-4 table-wrapper" 
      style="margin: 0 auto; float: none; display: block">
    <h5>REKENING SALDO</h5>
    <div class="balance-container">
      <div>Poin Masuk</div>
      <div>Poin Keluar</div>
      <div>Saldo</div>
      <div>Status</div>
      <div>Info</div>
    </div>
    <div id="balanceHistory"></div>
    <button id="loadMore" class="btn-submit">Load More</button>
  </div>
</section>


<section class="row">
  <div class="col-sm-12 col-md-6 col-lg-4 content privasi">
    <img class="ENEOS NXP-gray" src="{% static '/images/logo_putih.png' %}" style="width: 20%; margin-bottom: 16px;" />
    <p class="privasi-title">KEBIJAKAN PRIVASI</p>
    <p>Kami menjaga privasi segala bentuk <br /> informasi yang diterima</p>
  </div>
</section>

<section class="row">
  <div class="col-sm-12 col-md-6 col-lg-4 content backto-main">
    <p>Halaman Utama</p>
    <img class="payment-img" src="{% static '/images/back.png' %}" />
  </div>
</section>

<div class="modal fade" id="ModalCenter">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body top-body1" id="successBody">

      </div>

      <div class="modal-body bottom-body">
        <!-- <button type="button" class="btn-submit">Bagikan ke teman kamu</button> -->
        <button type="button" class="btn-close" data-dismiss="modal">Tutup</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="ModalCenter2">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- <div class="modal-body">
        <h4 style="text-align: center;"> Error ! </h4>
      </div> -->
      <div class="modal-body bottom-body">
        <div id="errorMessage"></div>
        <button type="button" class="btn-close" data-dismiss="modal">Tutup</button>
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block extra_js %}
<script>
  let nextPage = 0;
  function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
  }

  // SET INFO ON EVERY ROW
  function setInfo(redeem) {
    data = redeem.info
    serial_number = data.serial_number;
    let _body = `<img class="image1" src="{% static '/images/icon_big.png' %}" />`
    if (serial_number) {
      _body += `<p class='body-text first'>SCAN QRCODE</p>`;
      _body += `<p class='body-text '>Tanggal : ${data.datetime}</p>`;
      _body += `<p class='body-text '>Code : ${data.serial_number}</p>`;
      _body += `<p class='body-text '>Nominal : ${data.value}</p>`;
      _body += `<p class='body-text '>Status Transaksi : ${redeem.status}</p>`;
    } else {
      _body += `<p class='body-text first'>REDEEM REWARDS</p>`;
      _body += `<p class='body-text '>Tanggal : ${data.datetime}</p>`;
      _body += `<p class='body-text '>Nominal : ${data.value}</p>`;
      _body += `<p class='body-text '>Wallet : ${data.wallet_type}</p>`;
      _body += `<p class='body-text '>Status Transaksi : ${redeem.status}</p>`;
    }
    $("#successBody").html(_body);
    $('#ModalCenter').modal('show');
  }

  // RENDER DATA
  function renderData(response, fullRender) {
    nextPage = response.data.next_page;
    totalPage = response.data.total_page;
    if (nextPage > totalPage) {
      $("#loadMore").hide()
    } else {
      $("#loadMore").show()
    }

    if (fullRender) {
      $(".name").html(response.data.user.name)
      $(".mobile_number").html(response.data.user.mobile_number)
      $(".reward").html(`Rp. ${numberWithCommas(response?.data?.balance[0]?.balance)}.-`)
      $("#information").show()
      $("#nominal_value").show()
      $("#nominal_value2").show()
      $("#dealer_code").show()
      $("#btnRedeem").show()
      $("#balanceInfo").show()
      $("#walletType").show()
    }
    const balance = response.data.balance
    var _html = "";
    balance.map((bl, index) => {
      _html += `<div class="balance-container ${index % 2 == 0 ? 'odd' : ''}">
        <div>+ ${bl.credit}</div>
        <div>- ${bl.debit}</div>
        <div>${bl.balance}</div>
        <div>${bl.status}</div>
        <div onclick='setInfo(${JSON.stringify(bl)})' style='color:green'>Info</div>
      </div>`;
    });
    if (fullRender) {
      $("#balanceHistory").html(_html);
    } else {
      $("#balanceHistory").append(_html);
    }
  }

  // GET INFORMATION
  const userData = null;
  $("#mobile_number").val(localStorage.getItem("mobileNumber", ""));
  $("#searchButton").on('click', function () {
    const mobile_number = $("#mobile_number").val();
    $.ajax({
      type: 'POST',
      url: "{% url 'frontend:get_information' %}",
      data: {
        mobile_number: mobile_number
      },
      success: function (response) {
        renderData(response, true)
      },
      error: function (response) {
        let messageComp = document.getElementById("errorMessage");
        error = "Terjadi Kesalahan Server!"
        try {
          errorJSON = response.responseJSON;
          error = ""
          for (var key in errorJSON) {
            error += `<p style="color: red;"> ${errorJSON[key]}</p>`;
          }
        }
        catch (err) {
          console.log(err)
        }
        messageComp.innerHTML = error;
        $('#ModalCenter2').modal('show');

        $("#information").hide()
        $("#nominal_value").hide()
        $("#btnRedeem").hide()
        $("#balanceInfo").hide()
        $("#walletType").hide()
        $("#dealer_code").hide()
        $("#nominal_value2").hide()
      }
    });
  });

  // SUBMIT REDEEM
  $("#main-search-form").submit(function (e) {
    e.preventDefault();
    var serializedData = $(this).serialize();
    $.ajax({
      type: 'POST',
      url: "{% url 'frontend:api_redeem' %}",
      data: serializedData,
      success: function (response) {
        renderData(response, true)

        $("#nominal_value").val('')

        // show modal
        let _body = `<img class="image1" src="{% static '/images/icon_big.png' %}" />`
        _body += `<p class='body-text first'>SELAMAT</p>`;
        _body += `<p class='body-text '>Transaksi Anda Berhasil</p>`;
        $("#successBody").html(_body);
        $('#ModalCenter').modal('show');
      },
      error: function (response) {
        let messageComp = document.getElementById("errorMessage");
        error = "Terjadi Kesalahan Server!"
        try {
          errorJSON = JSON.parse(response.responseText);
          error = ""
          for (var key in errorJSON) {
            error += `<p style="color: red;"> ${errorJSON[key][0]}</p>`;
          }
        }
        catch (err) {
          console.log(err)
        }
        messageComp.innerHTML = error;
        $('#ModalCenter2').modal('show');
      }
    });
  });

  // IMASK FONT NUMBER
  // var element = document.getElementById('mobile_number');
  // var maskOptions = {
  //   mask: '+620000000000000'
  // };
  // var mask = IMask(element, maskOptions);
  $("#loadMore").on('click', function (e) {
    e.preventDefault();
    const mobile_number = $("#mobile_number").val();
    $.ajax({
      type: 'POST',
      url: "{% url 'frontend:load_balance' %}",
      data: {
        mobile_number: mobile_number,
        page: nextPage
      },
      success: function (response) {
        renderData(response, false)
      },
      error: function (response) {
        alert("Load data failed")
      }
    });
  })
</script>
{% endblock extra_js %}