nxp/backoffice/urls.py
from django.urls import path, include
from .views import login_view, log_out, index

app_name = "backoffice"
urlpatterns = [
    path('', index, name='index'),
    path('login/', login_view, name='login'),
    path('log_out/', log_out, name='log_out'),
    path('generate-qrcode/', include('nxp.backoffice.generate_qrcode.urls', namespace='generate_qrcode')),
    path('rewards/', include('nxp.backoffice.rewards.urls', namespace='rewards')),
    path('users/', include('nxp.backoffice.users.urls', namespace='users')),
]

nxp/backoffice/users/urls.py
from django.urls import path, include
from .views import *

app_name = "users"
urlpatterns = [
    path("", users, name="users"),
    path('<int:id>/user-detail/', user_detail, name='user_detail'),
]

nxp/frontend/urls.py
from django.urls import path
from .views import *

app_name = "frontend"
urlpatterns = [
    path('', scan, name='scan'),
    # path('', authenticated_scan, name='authenticated_scan'),
    path('redeem/', redeem, name='redeem'),
    path('api-scan/', scan, name='api_scan'),
    path('api-get-info/', get_information, name='get_information'),
    path('api-redeem/', api_redeem, name='api_redeem'),
    path('load-balance/', lazy_load_balance, name='load_balance'),

    # path('redeem/', redeem, name='redeem'),
    # path('api-scan/', api_scan, name='api_scan'),
    # path('api-get-info/', get_information, name='get_information'),
    # path('api-redeem/', api_redeem, name='api_redeem'),
    # path('load-balance/', lazy_load_balance, name='load_balance'),
]

nxp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "NXP Admin"
admin.site.site_title = "NXP Admin Portal"
admin.site.index_title = "Welcome to NXP Admin Portal"

urlpatterns = [
    path('', include('nxp.frontend.urls', namespace='frontend')),
    path('nxp-admin/', admin.site.urls),
    path('backoffice/', include('nxp.backoffice.urls', namespace='backoffice')),

    # redirect semua ke FE Home
    # path('nxp-admin/', include('nxp.frontend.urls', namespace='frontend2')),
    # path('backoffice/', include('nxp.frontend.urls', namespace='frontend3')),
    path('login', include('nxp.frontend.urls', namespace='frontend4')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nxp/apps/dealer/models.py
from django.db import models

from nxp.core.utils import FilenameGenerator


class Dealer(models.Model):
    code = models.CharField(max_length=50, unique=True, db_index=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

nxp/backoffice/forms.py
from django import forms
from django.contrib import auth


class LoginForm(auth.forms.AuthenticationForm):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

    def clean(self):
        return super(LoginForm, self).clean()

nxp/backoffice/generate_qrcode/forms.py
# from SahabatElvineDjango.apps.news.models import News
# from django import forms


# class AddNewsForm(forms.ModelForm):
#     name = forms.CharField(widget=forms.TextInput(
#         attrs={'class': 'form-control'}), required=False)
#     description = forms.CharField(
#         widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)
#     short_description = forms.CharField(
#         widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
#     picture1 = forms.ImageField(
#         required=True, help_text="Ukuran gambar harus 500PX * 270PX")
#     picture2 = forms.ImageField(required=False)
#     picture3 = forms.ImageField(required=False)
#     date = forms.ImageField(required=False)

#     class Meta:
#         model = News
#         fields = '__all__'

#     def clean_picture1(self):
#         picture1 = self.cleaned_data.get('picture1', False)
#         if picture1:
#             if picture1.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture1 file too large ( > 0.5mb )")
#         return picture1

#     def clean_picture2(self):
#         picture2 = self.cleaned_data.get('picture2', False)
#         if picture2:
#             if picture2.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture2 file too large ( > 0.5mb )")
#         return picture2

#     def clean_picture3(self):
#         picture3 = self.cleaned_data.get('picture3', False)
#         if picture3:
#             if picture3.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture3 file too large ( > 0.5mb )")
#         return picture3

nxp/apps/reward/views.py
from django.shortcuts import render

# Create your views here.

nxp/apps/serial_number/views.py
from django.shortcuts import render

# Create your views here.

nxp/apps/settings/views.py
from django.shortcuts import render

# Create your views here.

nxp/apps/user/views.py
from django.shortcuts import render

# Create your views here.

nxp/backoffice/generate_qrcode/views.py
import string
import random
import csv
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from django.http import JsonResponse

from nxp.apps.serial_number.models import SerialNumber
from nxp.apps.user.decorators import login_validate

from django.http import HttpResponse
from sequences import get_next_value
from django.db import transaction



@login_validate
def index(request):
    serials = SerialNumber.objects.all().order_by('-order')
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    start = request.GET.get("start", 0)
    end = request.GET.get("end", 0)

    if start and end:
        _filter = list(range(int(start), int(end)+1))
        serials = serials.filter(order__in=_filter)
    

    if search:
        serials = serials.filter(serial_number=search)

    status = request.GET.get("status")
    if status:
        serials = serials.filter(status=status)

    type = request.GET.get("type")
    if type:
        serials = serials.filter(type=type)

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
            # headers={'Content-Disposition': 'attachment; filename="qrcode.csv"'},
        )
        writer = csv.writer(response)
        writer.writerow(['No', 'Qr-Code', 'Status'])
        idx = 0
        for sr in serials:
            idx += 1
            writer.writerow([idx, sr.serial_number, sr.status])
        return response

    results_per_page = 60
    new_count = serials.filter(status="new").count()
    redeem_count = serials.filter(status="redeem").count()

    paginator = Paginator(serials, results_per_page)
    try:
        serials = paginator.get_page(page)
    except PageNotAnInteger:
        serials = paginator.get_page(1)
    except EmptyPage:
        serials = paginator.get_page(paginator.num_pages)

    context = {
        "serials": serials,
        "title": "Serial Number",
        "filter": {"search": search, "status": status, "type": type, "start": start, "end": end},
        "new_count": new_count,
        "redeem_count": redeem_count,
    }

    return TemplateResponse(request, "backoffice/serial/index.html", context)


def generate_serial(num):
    serials = []
    serials_str = []
    rp1000 = [1000] * int (1 * num)
    # rp500 = [500] * int (0.04 * num)
    # rp400 = [400] * int (0.93 * num)
    # list_value = rp1000 + rp500 + rp400
    list_value = rp1000

    for _ in range(num):
        duplicate = True
        while duplicate:
            code = "".join([random.choice(string.ascii_uppercase + string.digits) for i in range(
                10)])
            exists = code in serials_str
            serial = SerialNumber.objects.filter(serial_number=code).first()
            if not serial and not exists:
                serials_str.append(code)
                duplicate = False
        serial = SerialNumber(
            serial_number=code, order=get_next_value("order"), value=list_value.pop())
        serials.append(serial)
    SerialNumber.objects.bulk_create(serials)


def generate(request):
    amount = request.POST.get('amount', 0)
    if not int(amount) % 100 == 0:
        return JsonResponse({"status": "Jumlah harus kelipatan 100"}, safe=False, status=400)
    _type = request.POST.get('type')
    with transaction.atomic():
        generate_serial(int(amount))
    return JsonResponse({"status": "OK"}, safe=False)


def print_barcode(request):
    start = request.GET.get("start", 0)
    end = request.GET.get("end", 0)
    _filter = list(range(int(start), int(end)+1))
    serials = SerialNumber.objects.filter(order__in=_filter).order_by('-order')

    context = {
        "serials": serials,
        "title": "Print Number",
    }
    return TemplateResponse(request, "backoffice/serial/print.html", context)

nxp/backoffice/rewards/views.py
import csv
import datetime
from django.http import JsonResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.reward.models import Redeem, Scan
from nxp.apps.user.decorators import login_validate
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.http import HttpResponse


@login_validate
def redeem(request):
    redeems = Redeem.objects.select_related('user').order_by("-id")
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        redeems = redeems.filter(Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search))

    ewallet = request.GET.get("ewallet")
    if ewallet:
        redeems = redeems.filter(wallet_type=ewallet)
    status = request.GET.get("status")
    if status:
        redeems = redeems.filter(status=status)

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="redeem.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name', 'Nominal', 'E-Wallet', 'Status'])
        idx = 0
        for sr in redeems:
            idx += 1
            writer.writerow([idx, sr.user.name, sr.dealer_code, sr.user.mobile_number,
                             sr.value, sr.get_wallet_type_display(), sr.status])
        return response

    results_per_page = 30
    new_count = redeems.filter(status="new").count()
    paid_count = redeems.filter(status="paid").count()
    cancel_count = redeems.filter(status="paid").count()

    paginator = Paginator(redeems, results_per_page)
    try:
        redeems = paginator.get_page(page)
    except PageNotAnInteger:
        redeems = paginator.get_page(1)
    except EmptyPage:
        redeems = paginator.get_page(paginator.num_pages)

    context = {
        "redeems": redeems,
        "title": "Redeem",
        "filter": {"search": search, "status": status, "ewallet": ewallet},
        "new_count": new_count,
        "paid_count": paid_count,
        "cancel_count": cancel_count,
    }
    return TemplateResponse(request, "backoffice/rewards/index.html", context)


@login_validate
def transactions(request):
    scans = Scan.objects.all().order_by("-id").select_related('user')\
        .select_related('serial_number').order_by('-datetime')
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    start = request.GET.get("start", "")
    end = request.GET.get("end", "")
    if search:
        scans = scans.filter(
            Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search) | Q(serial_number__serial_number__icontains=search))

    if start and end:
        scans = scans.filter(datetime__range=[start, end])

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="transactions.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Serial', 'Name', 'Date', 'Value'])
        idx = 0
        
        for sr in scans:
            idx += 1
            _datetime = sr.datetime.strftime("%m/%d/%Y, %H:%M")
            _datetime = datetime.datetime.strptime(_datetime, "%m/%d/%Y, %H:%M")
            writer.writerow([idx, sr.serial_number, sr.user.name, _datetime,
                             sr.serial_number.value])
        return response

    results_per_page = 30
    paginator = Paginator(scans, results_per_page)
    try:
        scans = paginator.get_page(page)
    except PageNotAnInteger:
        scans = paginator.get_page(1)
    except EmptyPage:
        scans = paginator.get_page(paginator.num_pages)

    context = {
        "scans": scans,
        "title": "Transactions",
        "filter": {"search": search, "start": start, "end": end},
    }
    return TemplateResponse(request, "backoffice/rewards/transactions.html", context)

@login_validate
def redeem_detail(request, id):
    redeem = Redeem.objects.get(id=id)
    context = {
        "redeem": redeem,
        'vrer':  request.session
    }
    return TemplateResponse(request, "backoffice/rewards/redeem-detail.html", context)


@login_validate
def set_as_paid(request, id):
    redeem = get_object_or_404(Redeem, id=id)
    if redeem.status == 'paid':
        return JsonResponse({"message": "redeem already paid"}, status = 400)
    else:
        redeem.status = 'paid'
        redeem.paid_datetime = timezone.now()
        redeem.admin = request.user
        redeem.save()
        return JsonResponse({"message": "redeem already paid"}, status = 200)

    

nxp/backoffice/users/views.py
import csv
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.user.models import User
from nxp.apps.reward.models import Scan
from nxp.apps.user.decorators import login_validate
from django.http import HttpResponse


@login_validate
def users(request):
    users = User.objects.all().order_by("-id").exclude(is_superuser=True)
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        users = users.filter(
            Q(name__icontains=search) | Q(mobile_number__icontains=search) |
            Q(dealer_name__icontains=search)
        )

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="users.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name'])
        idx = 0
        for sr in users:
            idx += 1
            writer.writerow([idx, sr.name, sr.mobile_number, sr.dealer_name])
        return response

    results_per_page = 30
    paginator = Paginator(users, results_per_page)
    try:
        users = paginator.get_page(page)
    except PageNotAnInteger:
        users = paginator.get_page(1)
    except EmptyPage:
        users = paginator.get_page(paginator.num_pages)

    context = {
        "users": users,
        "title": "User",
        "filter": {"search": search},
    }
    return TemplateResponse(request, "backoffice/users/index.html", context)

@login_validate
def user_detail(request, id):
    user = User.objects.get(id=id)
    scans = Scan.objects.filter(user=user).order_by('-datetime').select_related('serial_number')
    context = {
        "user": user,
        "title": "User Detail",
        "scans": scans[0:8]
    }
    return TemplateResponse(request, "backoffice/users/user-detail.html", context)

nxp/backoffice/views.py
from django.apps.registry import apps
from django.contrib import messages
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from nxp.apps.reward.models import Redeem
from nxp.apps.user.decorators import login_validate
from nxp.backoffice.forms import LoginForm

get_model = apps.get_model


def login_view(request):
    auth_form = LoginForm(data=request.POST or None)
    if auth_form.is_valid():
        login(request, auth_form.get_user())
        auth_form.get_user()
        return redirect("backoffice:index")
    else:
        messages.error(request, "Username and Password are incorrect")

    list(messages.get_messages(request))
    context = dict(auth_form=auth_form,)
    return TemplateResponse(request, "backoffice/login.html", context)


def log_out(request):
    logout(request)
    return redirect("backoffice:login")


@login_validate
def index(request):
    redeems = Redeem.objects.all()
    context = dict(
        new_count=redeems.filter(status="new").count(),
        paid_count=redeems.filter(status="paid").count(),
        cancelled_count=redeems.filter(status="cancelled").count(),
        ovo_count=redeems.filter(wallet_type="ovo").count(),
        gopay_count=redeems.filter(wallet_type="gopay").count(),
        dana_count=redeems.filter(wallet_type="dana").count(),
        shopee_pay_count=redeems.filter(wallet_type="shopee_pay").count(),
        title='Dashboard'
    )
    return TemplateResponse(request, "backoffice/index.html", context)

nxp/templates/backoffice/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>{% block title %} {% endblock %}</title>
    {% block extra_header %} {% endblock %}

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <link href="{% static 'css/trackpad-scroll-emulator.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/chartist.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/jquery.raty.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/nouislider.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/explorer.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/sweetalert2.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/loading.css' %}" rel="stylesheet" type="text/css">
    <!-- <link href="/static/autocomplete_light/select2.css" rel="stylesheet" type="text/css"> -->
    <!-- <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/ico/sahabatelvine.ico'%}"> -->
  </head>
  <body class="">
    <div class="admin-wrapper">
      <div class="admin-sidebar">
        <div class="admin-sidebar-header">
          <div class="admin-sidebar-logo">
            <a href="/">
              <!-- <img src="{% static 'img/logo/logo.png' %}" class="svg" alt="Home"> -->
            </a>
            <a href="/" class="admin-sidebar-logo-title">
              <strong>ENEOS NXP OIL</strong>
              <span>-------------------------------</span>
            </a>
          </div>
          <!-- /.admin-sidebar-logo -->
        </div>
        <!-- /.admin-sidebar-header -->
        <div class="admin-sidebar-content">
          <h3>Menu</h3>
          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:index' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:index' %} active {% endif %}">
                  <i class="fa fa-tachometer"></i><span>Dashboard</span>
                </a>
            </li>
          </ul>


          <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:generate_qrcode:index' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:generate_qrcode:index' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>Generate QR-Code</span>
              </a>
            </li>
          </ul>


          <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:rewards:transactions' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:rewards:transactions' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>Transactions</span>
              </a>
            </li>
          </ul>

          <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:rewards:redeem' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:rewards:redeem' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>Redeem</span>
              </a>
            </li>
          </ul>
          <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:users:users' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:users:users' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>User</span>
              </a>
            </li>
          </ul>
        </div>
        <!-- /.admin-sidebar-content -->
        <div class="admin-sidebar-footer">
          <strong></strong>
          <span>&copy; ENEOS NXP OIL 2020</span>
        </div>
        <!-- /.admin-sidebar-footer -->
      </div>
      <!-- /.admin-sidebar -->
      <div class="admin-main">
        <div class="admin-header">
          <div class="container-fluid">
            
            <div class="admin-header-avatar">
              <!-- <span class="avatar" style="background-image: {% static 'images/user.png' %}"></span> -->
              <span class="admin-header-avatar-name">{{ request.user.username|title }}<i class="fa fa-chevron-down"></i></span>
              <ul class="admin-header-avatar-menu">
                <li><a href="#">{{ request.user.username|title }}</a></li>
                <li><a href="{% url 'backoffice:log_out' %}">Sign Out</a></li>
              </ul>
              <!-- /.admin-header-avatar-menu -->
            </div>
            <!-- /.admin-header-actions -->
          </div>
          <!-- /.container -->
        </div>
        <!-- /.admin-header -->
        <div class="admin-content">
          <div class="container-fluid">
            {% block breadcrumb %}
            <nav class="breadcrumb">
              <a class="breadcrumb-item" href="#">Home</a>
              <a class="breadcrumb-item" href="#">Library</a>
              <a class="breadcrumb-item" href="#">Data</a>
              <span class="breadcrumb-item active">Bootstrap</span>
            </nav>
            {% endblock %}

            {% block content %} {% endblock %}
            <!-- /.box -->
          </div>
          <!-- /.container -->
        </div>
        {% block footer %}
        <!-- /.admin-content -->
        <div class="admin-footer">
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-6">

              </div>
              <!-- /.col-* -->
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </div>
        {% endblock %}
      </div>
      <!-- /.admin-main -->
    </div>
    <!-- /.admin-wrapper -->

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/tether.min.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/chartist.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.trackpad-scroll-emulator.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.inlinesvg.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.affix.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.scrollTo.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/nouislider.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.raty.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/wNumb.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/explorer.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/sweetalert2.min.js' %}"></script> -->

    <script type="text/javascript">
      $(document).ready(function(){
        $(".delete").on('click', function(e) {
        e.preventDefault();
        swal({
          text: "Apakah anda yakin ?",
          cancelButtonColor: '#d33',
          showCancelButton: true,
          type: "info",
          customClass: 'swal-wide',
          confirmButtonColor: 'green',
          confirmButtonText: 'Yes'
          }).then((result) => {
              if (result.value) {
                window.location.href = this.getAttribute('href');
              } else {
                e.preventDefault();
                return false
              }
          })
        })
      })
    </script>
    {% block script %}
    {% endblock %}
  </body>
</html>

nxp/templates/backoffice/index.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% block title%} {{title}} {% endblock %}
{% block content %}

<div class="stats">
  <h3>Status</h3>
  <div class="row">
    <div class="col-md-6 col-lg-4">
      <a href="{% url 'backoffice:rewards:redeem'%}?status=new">
        <div class="stat-box" style="background-color: #eea73f;">
          <div class="stat-box-icon"><i class="fa fa-file"></i></div>
          <strong> {{ new_count | default:'0' }}</strong>
          <span>Formulir baru</span>
        </div>
      </a>
    </div>

    <div class="col-md-6 col-lg-4">
      <a href="{% url 'backoffice:rewards:redeem'%}?status=paid">
        <div class="stat-box" style="background-color: #60a853;">
          <div class="stat-box-icon"><i class="fa fa-file"></i></div>
          <strong> {{ paid_count | default:'0' }}</strong>
          <span>Formulir dibayar</span>
        </div>
      </a>
    </div>

    <div class="col-md-6 col-lg-4">
      <a href="{% url 'backoffice:rewards:redeem'%}?status=cancelled">
        <div class="stat-box" style="background-color: hsl(2, 74%, 53%);">
          <div class="stat-box-icon"><i class="fa fa-file"></i></div>
          <strong>{{ cancelled_count | default:'0' }}</strong>
          <span>Formulir di tolak</span>
        </div>
      </a>
    </div>
  </div>

  <h3>e-Wallet</h3>
  <div class="row">
    <div class="col-md-6 col-lg-3">
      <a href="{% url 'backoffice:rewards:redeem'%}?ewallet=ovo">
        <div class="stat-box" style="background-color: #755dad;">
          <div class="stat-box-icon"><i class="fa fa-map"></i></div>
          <strong>{{ ovo_count | default:'0'}}</strong>
          <span>OVO</span>
        </div>
      </a>
    </div>

    <div class="col-md-6 col-lg-3">
      <a href="{% url 'backoffice:rewards:redeem'%}?ewallet=gopay">
        <div class="stat-box" style="background-color: #44aad0;">
          <div class="stat-box-icon"><i class="fa fa-map"></i></div>
          <strong> {{ gopay_count | default:'0' }}</strong>
          <span>Gopay</span>
        </div>
      </a>
    </div>

    <div class="col-md-6 col-lg-3">
      <a href="{% url 'backoffice:rewards:redeem'%}?ewallet=dana">
        <div class="stat-box" style="background-color: #2b8ae3;">
          <div class="stat-box-icon"><i class="fa fa-map"></i></div>
          <strong>{{ dana_count | default:'0' }}</strong>
          <span>DANA</span>
        </div>
      </a>
    </div>

    <div class="col-md-6 col-lg-3">
      <a href="{% url 'backoffice:rewards:redeem'%}??ewallet=shopee_pay">
        <div class="stat-box" style="background-color: #e64b32;">
          <div class="stat-box-icon"><i class="fa fa-map"></i></div>
          <strong>{{ shopee_pay_count | default:'0' }}</strong>
          <span>Shopee Pay</span>
        </div>
      </a>
    </div>
  </div>
</div>

{% endblock %}